output.elf:
  rules: semu_rule.txt
  enable_native: false
  emulate_mode: emulate
  handlers:
    Delay: do_return
    HAL_Delay: do_return
    wait: do_return
    wait_us: do_return
    HAL_BE_ENET_ReadFrame: fuzzemu.handlers.common.hal_read_frame
    HAL_BE_In: fuzzemu.handlers.common.hal_in
    HAL_BE_Out: fuzzemu.handlers.common.hal_out
    HAL_BE_return_0: fuzzemu.handlers.common.return_zero
    HAL_BE_return_1: fuzzemu.handlers.common.return_true
    HAL_BE_Block_Read: fuzzemu.handlers.common.hal_block_in
    HAL_BE_Block_Write: fuzzemu.handlers.common.hal_block_out
  mmio_funcs:
  - APPD_SetCPU2GpioConfig
  - HAL_GPIO_DeInit
  - RescheduleTimerList
  - RestartWakeupCounter
  - ReadRtcSsrValue
  - HW_TS_RTC_Wakeup_Handler
  - HW_UART_Transmit
  - HW_UART_Transmit_IT
  - HW_UART_Receive_IT
  - SystemClock_Config
  - UART_SetConfig
  - HAL_RCCEx_PeriphCLKConfig
  - UART_RxISR_16BIT_FIFOEN
  - UART_RxISR_16BIT
  - UART_TxISR_16BIT_FIFOEN
  - UART_TxISR_16BIT
  - HAL_PWREx_DisableLowPowerRunMode
  - HAL_PWREx_ControlVoltageScaling
  - HAL_RCC_ClockConfig
  - HAL_RCC_OscConfig
  - BSP_PB_Init
  - HAL_GPIO_Init
  - HAL_DMA_PollForTransfer
  - FLASH_WaitForLastOperation
  - HAL_FLASH_IRQHandler
  - RCC_SetFlashLatency
  - UART_WaitOnFlagUntilTimeout
  - UART_CheckIdleState
  - HAL_UART_IRQHandler
  - HAL_UART_AbortReceive_IT
  - HAL_UART_AbortTransmit_IT
  - HAL_UART_Abort_IT
  - HAL_UART_AbortReceive
  - HAL_UART_AbortTransmit
  - HAL_UART_Abort
  - HAL_UART_DMAStop
  - HAL_UART_DMAPause
  - HAL_RNG_GenerateRandomNumber
  - HAL_RTCEx_SetWakeUpTimer_IT
  - HAL_RTCEx_SetWakeUpTimer
  - HAL_TIMEx_PWMN_Stop_IT
  - HAL_TIMEx_OCN_Stop_IT
  - HAL_TIM_IC_Stop_DMA
  - HAL_TIM_IC_Stop_IT
  - HAL_TIM_IC_Stop
  - HAL_TIM_PWM_Stop_DMA
  - HAL_TIM_PWM_Stop_IT
  - HAL_TIM_PWM_Stop
  - HAL_TIM_OC_Stop_DMA
  - HAL_TIM_OC_Stop_IT
  - HAL_TIM_OC_Stop
  - HAL_TIMEx_PWMN_Stop_DMA
  - HAL_TIMEx_PWMN_Stop
  - HAL_TIMEx_OCN_Stop_DMA
  - HAL_TIMEx_OCN_Stop
  - HAL_TIMEx_OnePulseN_Stop_IT
  - HAL_TIMEx_OnePulseN_Stop
  - UART_Start_Receive_DMA
  - UART_Start_Receive_IT
  - HAL_UART_Receive_DMA
  - HAL_UART_Transmit_DMA
  - HAL_UART_Receive_IT
  - HAL_UART_Transmit_IT
  - HAL_UART_Receive
  - HAL_UART_Transmit
  - HAL_UARTEx_ReceiveToIdle_DMA
  - HAL_UARTEx_ReceiveToIdle_IT
  - HAL_UARTEx_ReceiveToIdle
  - UART_RxISR_8BIT_FIFOEN
  - UART_RxISR_8BIT
  - HW_TS_Stop
  - HAL_RTC_WaitForSynchro
  - HAL_RTC_PollForAlarmAEvent
  - HAL_RTC_SetAlarm_IT
  - HAL_RTCEx_PollForAlarmBEvent
  - HAL_RTCEx_PollForWakeUpTimerEvent
  - HAL_RTCEx_PollForTamper3Event
  - HAL_RTCEx_PollForTamper2Event
  - HAL_RTCEx_PollForTamper1Event
  - HAL_RTCEx_PollForTimeStampEvent
  - HAL_RTC_DeInit
  - HAL_TIM_Encoder_Stop_DMA
  - HAL_TIM_Encoder_Stop_IT
  - HAL_TIM_Encoder_Stop
  - HAL_TIM_OnePulse_Stop_IT
  - HAL_TIM_OnePulse_Stop
  - HAL_TIMEx_HallSensor_Stop_DMA
  - HAL_TIMEx_HallSensor_Stop_IT
  - HAL_TIMEx_HallSensor_Stop
  - ExitLowPower
  - UART_DMAReceiveCplt
  - UART_TxISR_8BIT_FIFOEN
  - UART_TxISR_8BIT
  - HAL_UART_DMAResume
  - HAL_TIM_Encoder_DeInit
  - HAL_TIM_OnePulse_DeInit
  - HAL_TIM_IC_DeInit
  - HAL_TIM_PWM_DeInit
  - HAL_TIM_OC_DeInit
  - HAL_TIM_Base_Stop_DMA
  - HAL_TIM_Base_Stop_IT
  - HAL_TIM_Base_Stop
  - HAL_TIM_Base_DeInit
  - HAL_TIMEx_HallSensor_DeInit
  - HAL_RCC_DeInit
  - HAL_RTC_SetAlarm
  - HAL_RTCEx_SetSynchroShift
  - HAL_RTCEx_SetSmoothCalib
  - HAL_TIMEx_ReArmBreakInput
  - HAL_RCCEx_CRSWaitSynchronization
  - MX_APPE_Config
  - HAL_SYSCFG_EnableVREFBUF
  - FLASH_Program_Fast
  - RTC_EnterInitMode
  - HAL_RTC_DeactivateAlarm
  - HAL_RTCEx_DeactivateWakeUpTimer
  - UART_DMATransmitCplt
  - UART_EndTransmit_IT
  - UART_EndRxTransfer
  - UART_EndTxTransfer
  - HAL_HalfDuplex_EnableReceiver
  - HAL_HalfDuplex_EnableTransmitter
  - HAL_MultiProcessor_DisableMuteMode
  - HAL_MultiProcessor_EnableMuteMode
  - HAL_UARTEx_DisableStopMode
  - HAL_UARTEx_EnableStopMode
