db_path: /home/chenkaiqiu/LCMHalMCPServer/zephyr-driver-db
proj_path: /home/chenkaiqiu/LCMHalMCPServer/testcases/eth_driver
script_path: /home/chenkaiqiu/LCMHalMCPServer/testcases/eth_driver
src_path: /home/chenkaiqiu/LCMHalMCPServer/testcases/eth_driver
