# LCMHAL配置文件
script_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalMCPServer/testcases/macbook/rtthread_ymodem"
db_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalTest_DBS/DATABASE_RTThreadYmodem"
src_path: "/Users/jie/Documents/workspace/lcmhalgen/rt-thread/examples/ymodem"
proj_path: "/Users/jie/Documents/workspace/lcmhalgen/rt-thread/bsp/hifive1"