# LCMHAL配置文件
script_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalMCPServer/testcases/macbook/nxp_bm_uart_dma"
db_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalTest_DBS/DATABASE_NXP_BMUART_DMA_macbook"
src_path: "/Users/jie/mcuxpresso-sdk"
proj_path: "/Users/jie/mcuxpresso-sdk"
