emulate_mode: emulate
enable_native: false
entry_point: 0x80012fd
handlers:
  Delay: do_return
  HAL_BE_Block_Read: fuzzemu.handlers.common.hal_block_in
  HAL_BE_Block_Write: fuzzemu.handlers.common.hal_block_out
  HAL_BE_ENET_ReadFrame: fuzzemu.handlers.common.hal_read_frame
  HAL_BE_In: fuzzemu.handlers.common.hal_in
  HAL_BE_Out: fuzzemu.handlers.common.hal_out
  HAL_BE_return_0: fuzzemu.handlers.common.return_zero
  HAL_BE_return_1: fuzzemu.handlers.common.return_true
  HAL_Delay: do_return
  wait: do_return
  wait_us: do_return
include:
- ./syms.yml
initial_sp: 0xffffffff
isr_vector: 0x0
memory_map:
  flash:
    base_addr: 0x8000000
    file: output.bin
    permissions: r-x
    size: 0xd9c60
  irq_ret:
    base_addr: 0xfffff000
    permissions: rwx
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  peripheral:
    base_addr: 0xa0000000
    permissions: rw-
    size: 0x40000000
  peripheral_ram:
    base_addr: 0x60000000
    permissions: rw-
    size: 0x40000000
  ram:
    base_addr: 0x20000000
    permissions: rwx
    size: 0x400000
mmio_funcs:
- mcuxClEls_LimitedWaitForOperation
- mcuxClEls_WaitForOperation
- LoadGdetCfg
- CLOCK_GetAvPllCh2Freq
- CLOCK_GetAvPllCh1Freq
- otp_get_nonmask_status_result
- CACHE64_Init
- CACHE64_GetInstance
- FLEXSPI_TransferHandleIRQ
- FLEXSPI_ReadBlocking
- FLEXSPI_WriteBlocking
- FLEXSPI_UpdateAhbBuffersSettings
- FLEXSPI_Init
- PINT_DisableCallback
- PINT_EnableCallback
- PINT_PinInterruptClrStatusAll
- PINT0_DriverIRQHandler
- ENET_GetInstance
- FLEXSPI_GetInstance
- PINT_GetInstance
- CLOCK_InitT3RefClk
- mcuxClEls_ResetErrorFlags
- initFlexSPI
- BOARD_InitFlash
- FLEXSPI_UpdateLUT
- FLEXSPI_UpdateDllValue
- mcuxClEls_setOutput_fixedSize
- mcuxClEls_setOutput
- mcuxClEls_setInput2_fixedSize
- mcuxClEls_setInput2
- mcuxClEls_setInput1_fixedSize
- mcuxClEls_setInput0_fixedSize
- mcuxClEls_setInput0
- CLOCK_EnableUsbhsPhyClock
- soc_otp_read
- ENET_ReceiveIRQHandler
- ENET_TransmitIRQHandler
- HAL_GpioSetTriggerMode
- HAL_GpioDeinit
- FLEXSPI_TransferBlocking
- OCOTP_OtpFuseRead
- ENET_SetMacController
- POWER_TrimSvc
- CLOCK_InitTddrRefClk
- CLOCK_InitTcpuRefClk
- CLOCK_EnableClock
- CACHE64_CleanInvalidateCache
- CACHE64_CleanCache
- CACHE64_InvalidateCache
- RESET_ClearPeripheralReset
- RESET_SetPeripheralReset
- POWER_PowerOffBle
- POWER_PowerOnBle
- POWER_PowerOffWlan
- POWER_PowerOnWlan
- CACHE64_CleanInvalidateCacheByRange
- CACHE64_CleanCacheByRange
- CACHE64_InvalidateCacheByRange
- BOARD_InitPsRam
- FLEXSPI_SoftwareReset
- ENET_LeaveMulticastGroup
- ENET_AddMulticastGroup
- CLOCK_EnableAvPllCh
- CLOCK_EnableXtal32K
- POWER_PowerOnGau
- BOARD_DeinitFlash
- otp_wait_busy
- deinitXip
- SystemInit
- ENET_GetRxFrame
- ENET_MDIOWaitTransferOver
- BOARD_SetFlexspiClock
- mcuxClEls_GlitchDetector_ResetEventCounter
model: semu
rules: semu_rule.txt
