# LCMHAL配置文件
script_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalMCPServer/testcases/macbook/rtthread_network"
db_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalTest_DBS/DATABASE_RTThreadNetwork"
src_path: "/Users/jie/Documents/workspace/lcmhalgen/rt-thread/examples/network"
proj_path: "/Users/jie/Documents/workspace/lcmhalgen/rt-thread/bsp/hifive1"