# LCMHAL配置文件
script_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalMCPServer/testcases/macbook/nxp_freertos_httpsrv"
db_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalTest_DBS/DATABASE_NXP_FreeRTOSHTTPSrv_macbook"
src_path: "/Users/jie/mcuxpresso-sdk"
proj_path: "/Users/jie/mcuxpresso-sdk"
