board: nucleo_f429zi
target_arch: arm
build_system: zephyr
build_dir: build
src_dir: src
emulate_dir: emulate
codeql_db_dir: codeql_db
codeql_queries_dir: ../queries
codeql_pack: codeql-pack.yml
codeql_compile_commands: compile_commands.json
codeql_extractor: cpp
codeql_analysis_timeout: 300
emulator: fuzzemu
emulator_timeout: 30
emulator_input: base_input/input.bin
emulator_config: base_config.yml
emulator_output: debug_output
analysis_mode: full
skip_build: false
skip_emulation: false
skip_codeql: false
log_level: INFO
db_path: /home/chenkaiqiu/LCMHalMCPServer/testcases/zephyr_eth_official/codeql_db
proj_path: /home/chenkaiqiu/LCMHalMCPServer/testcases/zephyr_eth_official
script_path: /home/chenkaiqiu/LCMHalMCPServer/testcases/zephyr_eth_official
src_path: /home/chenkaiqiu/LCMHalMCPServer/testcases/zephyr_eth_official/src
