# LCMHAL配置文件
script_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalMCPServer/testcases/macbook/rt-thread/var_export"
db_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalTest_DBS/DATABASE_RTThreadVarexport"
src_path: "/Users/jie/Documents/workspace/lcmhalgen/rt-thread/examples/var_export"
proj_path: "/Users/jie/Documents/workspace/lcmhalgen/rt-thread/bsp/hifive1"