db_path: /Users/jie/Documents/workspace/lcmhalgen/LCMHalTest_DBS/DATABASE_FreeRTOSLwIP_StreamingServer
proj_path: /home/haojie/posixGen_Demos/LwIP_StreamingServer
script_path: /Users/jie/Documents/workspace/lcmhalgen/LCMHalMCPServer/testcases/macbook/freertos_streamserver
src_path: /Users/jie/Documents/workspace/lcmhalgen/posixGen_Demos/LwIP_StreamingServer
