# LCMHAL配置文件
script_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalMCPServer/testcases/macbook/freertos_uart"
db_path: "/Users/jie/Documents/workspace/lcmhalgen/LCMHalTest_DBS/DATABASE_FreeRTOSUART_Hyperterminal_IT"
src_path: "/Users/jie/Documents/workspace/lcmhalgen/posixGen_Demos/UART_Hyperterminal_IT"
proj_path: "/Users/jie/Documents/workspace/lcmhalgen/posixGen_Demos/UART_Hyperterminal_IT"
