emulate_mode: emulate
enable_native: false
entry_point: 0x802966d
handlers:
  Delay: do_return
  HAL_BE_Block_Read: fuzzemu.handlers.common.hal_block_in
  HAL_BE_Block_Write: fuzzemu.handlers.common.hal_block_out
  HAL_BE_ENET_ReadFrame: fuzzemu.handlers.common.hal_read_frame
  HAL_BE_In: fuzzemu.handlers.common.hal_in
  HAL_BE_Out: fuzzemu.handlers.common.hal_out
  HAL_BE_return_0: fuzzemu.handlers.common.return_zero
  HAL_BE_return_1: fuzzemu.handlers.common.return_true
  HAL_Delay: do_return
  wait: do_return
  wait_us: do_return
include:
- ./syms.yml
initial_sp: 0x20080000
isr_vector: 0x0
memory_map:
  flash:
    base_addr: 0x8000000
    file: output.bin
    permissions: r-x
    size: 0x2ced74
  irq_ret:
    base_addr: 0xfffff000
    permissions: rwx
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  peripheral:
    base_addr: 0xa0000000
    permissions: rw-
    size: 0x40000000
  peripheral_ram:
    base_addr: 0x60000000
    permissions: rw-
    size: 0x40000000
  ram:
    base_addr: 0x20000000
    permissions: rwx
    size: 0x400000
mmio_funcs:
- HAL_I2C_Mem_Read
- HAL_I2C_Mem_Write
- HAL_I2C_Slave_Receive
- HAL_I2C_Slave_Transmit
- HAL_I2C_Master_Receive
- HAL_I2C_Master_Transmit
- HAL_DMA2D_CLUTLoading_Abort
- HAL_DMA2D_CLUTLoading_Suspend
- ETH_Prepare_Tx_Descriptors
- BSP_SDRAM_MspInit
- BSP_SD_MspInit
- BSP_SRAM_MspInit
- HAL_DMA_Init
- BSP_CAMERA_MspInit
- HAL_GPIO_DeInit
- I2C_IsErrorOccurred
- BSP_COM_Init
- BSP_PB_Init
- BSP_LED_Init
- MFX_IO_ITConfig
- BSP_POTENTIOMETER_Init
- I2Cx_MspInit
- BSP_LCD_Reset
- BSP_LCD_MspInit
- HAL_PWREx_DisableOverDrive
- HAL_PWREx_EnableOverDrive
- HAL_RCCEx_PeriphCLKConfig
- HAL_RCC_MCOConfig
- HAL_RCC_OscConfig
- HAL_GPIO_Init
- HAL_ETH_MspInit
- HAL_ETH_Init
- HAL_I2CEx_DisableFastModePlus
- HAL_I2CEx_EnableFastModePlus
- HAL_DSI_ExitULPM
- HAL_DSI_EnterULPM
- HAL_DSI_ExitULPMData
- HAL_DSI_Stop
- HAL_DSI_Start
- HAL_DSI_DeInit
- HAL_DSI_Init
- HAL_PWREx_EnterUnderDriveSTOPMode
- HAL_PWREx_ControlVoltageScaling
- HAL_InitTick
- SystemClock_Config
- HAL_I2C_IsDeviceReady
- HAL_FLASHEx_Erase
- ETH_DMARxDescListInit
- ETH_DMATxDescListInit
- HAL_RCC_ClockConfig
- HAL_DMA_IRQHandler
- HAL_DMA_Abort
- HAL_DMA2D_PollForTransfer
- HAL_DMA2D_Abort
- HAL_DMA2D_Suspend
- UART_SetConfig
- HAL_TIMEx_OnePulseN_Stop_IT
- HAL_TIMEx_OnePulseN_Stop
- HAL_TIMEx_PWMN_Stop_DMA
- HAL_TIMEx_PWMN_Stop_IT
- HAL_TIMEx_PWMN_Stop
- HAL_TIMEx_OCN_Stop_DMA
- HAL_TIMEx_OCN_Stop_IT
- HAL_TIMEx_OCN_Stop
- HAL_TIMEx_HallSensor_Stop_DMA
- HAL_TIMEx_HallSensor_Stop_IT
- HAL_TIMEx_HallSensor_Stop
- HAL_TIM_Encoder_Stop_DMA
- HAL_TIM_Encoder_Stop_IT
- HAL_TIM_Encoder_Stop
- HAL_TIM_OnePulse_Stop_IT
- HAL_TIM_OnePulse_Stop
- HAL_TIM_IC_Stop_DMA
- HAL_TIM_IC_Stop_IT
- HAL_TIM_IC_Stop
- HAL_TIM_PWM_Stop_DMA
- HAL_TIM_PWM_Stop_IT
- HAL_TIM_PWM_Stop
- HAL_TIM_OC_Stop_DMA
- HAL_TIM_OC_Stop_IT
- HAL_TIM_OC_Stop
- HAL_ETH_ReadPHYRegister
- HAL_ETH_WritePHYRegister
- HAL_RCCEx_EnablePLLSAI
- HAL_RCCEx_EnablePLLI2S
- HAL_DSI_Read
- I2C_WaitOnRXNEFlagUntilTimeout
- HAL_ETH_Transmit
- ETH_UpdateDescriptor
- HAL_ETH_ReadData
- HAL_ETH_Transmit_IT
- HAL_ETH_SetWakeUpFilter
- HAL_DSI_LongWrite
- I2C_WaitOnFlagUntilTimeout
- HAL_PWREx_DisableBkUpReg
- HAL_TIMEx_HallSensor_DeInit
- HAL_TIM_Encoder_DeInit
- HAL_TIM_OnePulse_DeInit
- HAL_TIM_IC_DeInit
- HAL_TIM_PWM_DeInit
- HAL_TIM_OC_DeInit
- HAL_TIM_Base_Stop_DMA
- HAL_TIM_Base_Stop_IT
- HAL_TIM_Base_Stop
- HAL_TIM_Base_DeInit
- HAL_PWREx_EnableBkUpReg
- HAL_DSI_EnterULPMData
- HAL_RCCEx_DisablePLLSAI
- HAL_RCCEx_DisablePLLI2S
- HAL_RCC_DeInit
- HAL_ETH_ReleaseTxPacket
- FLASH_WaitForLastOperation
- HAL_LTDC_DeInit
- DSI_ShortWrite
- I2C_WaitOnSTOPFlagUntilTimeout
- I2C_WaitOnTXISFlagUntilTimeout
model: semu
rules: semu_rule.txt
